Add Scratch to Just-Install
just-install/registry pull request #255
Opened 2021-05-25 04:05 UTC by danielsherratt

2021-05-28 14:27 UTC, mimi89999 commented on just-install-v4.json
> +	"audacity": {
Please fix indent

2021-05-28 14:28 UTC, mimi89999 requested changes
Please fix indent

2021-05-30 10:13 UTC, mimi89999 commented
Please rebase on master

2021-05-31 06:57 UTC, closed without merging

2021-05-31 06:57 UTC, danielsherratt commented
Using winget